### ISSUE TITLE
A descriptive title of the issue

### ISSUE THREAD

**Issue by hudson-s** [small-hack/coturn-chart#110]
## Describe your Issue

Port 5349 behind the lb is unavailable
but, 3478 port is available
### Logs and Errors
```
# Give us any logs or errors you're getting here
```

## Describe your Environment

- Kubernetes distribution: 

- Helm Version (or App that manages helm): 

- Helm Chart Version: 

- `values.yaml`:
  ports:
    -- minimum ephemeral port for coturn
    min: 49152
    -- maximum ephemeral port for coturn
    max: 65535
  -- insecure listening port
    listening: 3478
     -- secure listening port
    tlsListening: 5349
```yaml
# anonymize any sensitive data and then paste your values.yaml here
```

**Comment by PelikanFix16** [comment]
I had the same issue today. The problem is that TURNS cannot establish a connection over UDP, it requires TCP. The current chart creates two separate services:

- One for UDP
- One for TCP

This is unnecessary. Instead, a single Service can handle both protocols on the same ports. Here’s what works:

```
apiVersion: v1
kind: Service
metadata:
  name: coturn-lb
  namespace: coturn
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: turn-udp
      port: 3478
      targetPort: 3478
      protocol: UDP
    - name: turn-tcp
      port: 3478
      targetPort: 3478
      protocol: TCP
    - name: turn-tls-udp
      port: 5349
      targetPort: 5349
      protocol: UDP
    - name: turn-tls-tcp
      port: 5349
      targetPort: 5349
      protocol: TCP
  selector:
    app.kubernetes.io/name: coturn-coturn
    app.kubernetes.io/instance: coturn
```

This setup works fine, avoids redundancy, and ensures TURNS works properly. The chart should be updated to use a single service instead of two.
