### ISSUE TITLE
I used lb. Let's talk about it

### ISSUE THREAD

**Issue by hudson-s** [small-hack/coturn-chart#136]
My `values.yaml` are as follows

```
service:
  # -- The type of service to deploy for routing Coturn traffic.
  #   ClusterIP: Recommended for DaemonSet configurations. This will create a
  #              standard Kubernetes service for Coturn within the cluster.
  #              No external networking will be configured as the DaemonSet
  #              will handle binding to each Node's host networking
  #
  #   NodePort:  Recommended for Deployment configurations. This will open
  #              TURN ports on every node and route traffic on these ports to
  #              the Coturn pods. You will need to make sure your cloud
  #              provider supports the cluster config setting,
  #              apiserver.service-node-port-range, as this range must contain
  #              the ports defined above for the service to be created.
  #
  #   LoadBalancer: This was what was originally set for this chart in the
  #                 upstream of this fork, but with no details
 
  type: **LoadBalancer**
 
  externalTrafficPolicy: "Local"
```

![image](https://github.com/user-attachments/assets/603956c6-dad3-44d5-8ca7-8e4a9a6bdc14)

During my deployment with this project, I found that no turn public ip was leaked. So I switched to lb. How did you leak the public ip address?

Sudden leakage after the public IP test turn can use https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ server is running
