### ISSUE TITLE
Does not work for NodePort

### ISSUE THREAD

**Issue by CASL0** [small-hack/coturn-chart#75]
## Describe your Issue
It doesn't work for NodePort, because NodePort cannot use the same port.

### Logs and Errors
```
Error: UPGRADE FAILED: cannot patch "myrelease-turn-udp" with kind Service: Service "myrelease-turn-udp" is invalid: spec.ports[0].nodePort: Invalid value: 30030: provided port is already allocated
```

## Describe your Environment

- Kubernetes distribution: kind

- Helm Version (or App that manages helm): 3.13.3

- Helm Chart Version: 4.3.0

- `values.yaml`:

```yaml
coturn:
  realm: "localhost"
  auth:
    password: "password"
  ports:
    tlsListening: 30030
    listening: 30031
service:
  type: NodePort
```

## Additional context, if any
a typo in ".Values.coturn.ports" as ".Values.coturn.port," so you need to correct it together.
